### ISSUE TITLE
Installation Fails

### ISSUE THREAD

**Issue by Ravencentric** [TMD20/Remuxer#29]
```
(env) USERNAME@PC:/mnt/c/Users/USERNAME/Documents/GitHub/PT-Muxer$ pip3 install -r requirements.txt
ERROR: Exception:
Traceback (most recent call last):
  File "/mnt/c/Users/USERNAME/Documents/GitHub/PT-Muxer/env/lib/python3.10/site-packages/pip/_vendor/packaging/markers.py", line 278, in __init__
    self._markers = _coerce_parse_result(MARKER.parseString(marker))
  File "/mnt/c/Users/USERNAME/Documents/GitHub/PT-Muxer/env/lib/python3.10/site-packages/pip/_vendor/pyparsing/core.py", line 1134, in parse_string
    raise exc.with_traceback(None)
pip._vendor.pyparsing.exceptions.ParseException: Expected {Group:({'implementation_version' | 'platform_python_implementation' | 'implementation_name' | 'python_full_version' | 'platform_release' | 'platform_version' | 'platform_machine' | 'platform_system' | 'python_version' | 'sys_platform' | 'os_name' | 'os.name' | 'sys.platform' | 'platform.version' | 'platform.machine' | 'platform.python_implementation' | 'python_implementation' | 'extra'} | {string enclosed in "'" | string enclosed in '"'}} {'===' | '==' | '>=' | '<=' | '!=' | '~=' | '>' | '<' | 'not in' | 'in'} {{'implementation_version' | 'platform_python_implementation' | 'implementation_name' | 'python_full_version' | 'platform_release' | 'platform_version' | 'platform_machine' | 'platform_system' | 'python_version' | 'sys_platform' | 'os_name' | 'os.name' | 'sys.platform' | 'platform.version' | 'platform.machine' | 'platform.python_implementation' | 'python_implementation' | 'extra'} | {string enclosed in "'" | string enclosed in '"'}) | Group:({{Suppress:('(') : ...} Suppress:(')')})}, found 'pytho'  (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/USERNAME/Documents/GitHub/PT-Muxer/env/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/mnt/c/Users/USERNAME/Documents/GitHub/PT-Muxer/env/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/mnt/c/Users/USERNAME/Documents/GitHub/PT-Muxer/env/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 305, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "/mnt/c/Users/USERNAME/Documents/GitHub/PT-Muxer/env/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 439, in get_requirements
    req_to_add = install_req_from_parsed_requirement(
  File "/mnt/c/Users/USERNAME/Documents/GitHub/PT-Muxer/env/lib/python3.10/site-packages/pip/_internal/req/constructors.py", line 463, in install_req_from_parsed_requirement
    req = install_req_from_line(
  File "/mnt/c/Users/USERNAME/Documents/GitHub/PT-Muxer/env/lib/python3.10/site-packages/pip/_internal/req/constructors.py", line 390, in install_req_from_line
    parts = parse_req_from_line(name, line_source)
  File "/mnt/c/Users/USERNAME/Documents/GitHub/PT-Muxer/env/lib/python3.10/site-packages/pip/_internal/req/constructors.py", line 295, in parse_req_from_line
    markers = Marker(markers_as_string)
  File "/mnt/c/Users/USERNAME/Documents/GitHub/PT-Muxer/env/lib/python3.10/site-packages/pip/_vendor/packaging/markers.py", line 280, in __init__
    raise InvalidMarker(
pip._vendor.packaging.markers.InvalidMarker: Invalid marker: 'pytho', parse error at 'pytho'
```

**Comment by TMD20** [comment]
Hey so I was able to recreate the error you got

It seems their was an error with the requirements.txt file
I reran the command so the new version should work

**Comment by TMD20** [comment]
Since this issue seems to be fixed I'm going to close it now
